// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOHE_gmO9nNwZf-0SjPtcmTzc8vBJut2o',
    appId: '1:227049695673:web:c06adc102a5610c5ef2e68',
    messagingSenderId: '227049695673',
    projectId: 'newchat-63294',
    authDomain: 'newchat-63294.firebaseapp.com',
    storageBucket: 'newchat-63294.appspot.com',
    measurementId: 'G-B9K05KTC19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcle19Vx7Zd7vVHkSo9P5dlQvNqtesdcI',
    appId: '1:227049695673:android:48f3c3422b96a97fef2e68',
    messagingSenderId: '227049695673',
    projectId: 'newchat-63294',
    storageBucket: 'newchat-63294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAZnaajwZ9bhg7xOKUqVx7xlj8acCKHPA',
    appId: '1:227049695673:ios:4885c4a2f4914e1eef2e68',
    messagingSenderId: '227049695673',
    projectId: 'newchat-63294',
    storageBucket: 'newchat-63294.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAZnaajwZ9bhg7xOKUqVx7xlj8acCKHPA',
    appId: '1:227049695673:ios:4885c4a2f4914e1eef2e68',
    messagingSenderId: '227049695673',
    projectId: 'newchat-63294',
    storageBucket: 'newchat-63294.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOHE_gmO9nNwZf-0SjPtcmTzc8vBJut2o',
    appId: '1:227049695673:web:ac1df4e03e2eb7c9ef2e68',
    messagingSenderId: '227049695673',
    projectId: 'newchat-63294',
    authDomain: 'newchat-63294.firebaseapp.com',
    storageBucket: 'newchat-63294.appspot.com',
    measurementId: 'G-H9SHEVZQC7',
  );
}
